-- Project Euler Question 2
-- Author: Corentin Pinato
-- Date: 24 May 2018
--------------------------------------------------------------------------------
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed
-- four million, find the sum of the even-valued terms.
--------------------------------------------------------------------------------

fibonacci :: [Integer]
fibonacci = 1 : 1 : zipWith (+) fibonacci (tail fibonacci)

n_fib :: Int -> Integer
n_fib n = fibonacci !! n

fibs :: Integer -> Integer -> [Integer]
fibs m n = do
  if fib < m then [fib] ++ fibs m (n+1) else []
  where fib = n_fib $ fromIntegral n

euler_2 :: Integer -> Integer
euler_2 n = sum $ filter even $ fibs n 0

main = do
  print $ euler_2 4000000
